# This is a basic workflow to help you get started with Actions

name: deploy python to lambda

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: install dependencies
        run: |
          python3 -m venv lib/
          source lib/bin/activate
          pip3 install -r requirements.txt
          deactivate
          
      - name: move lambda function
        run: cp ./lambda_function.py ./lib/lib/python3.9/site-packages/lambda_function.py 
      
      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: zip -qq -r .bundle.zip ./
        working-directory: ./lib/lib/python3.9/site-packages/

      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_region: us-east-1
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          function_name: news-scraper
          zip_file: bundle.zip
